import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Delta for Business Glossary | Key Terms Explained',
  description:
    'Definitions for Delta for Business terms: MQD, eCredits, SkyMiles, Corporate Priority, Business ID, SMB tiers, Medallion, Delta Business Tool, and more.',
  alternates: { canonical: 'https://business.delta.com/resources/glossary' },
}

const terms = [
  { term: 'Business ID', def: 'A unique alphanumeric code assigned to your company when you enroll in Delta for Business. Travelers enter this at booking to link flights to the company account.' },
  { term: 'Company Miles', def: 'Miles earned by your company account (not individual employees) on eligible Delta flights. Separate from employee personal SkyMiles. Redeemable as eCredits, transfers, Sky Club memberships, or Silver Medallion certificates.' },
  { term: 'Corporate Priority', def: 'A suite of six travel benefits available to mid-market and enterprise corporate accounts: preferred seating, Zone 1 boarding, upgrade certificates, service recovery priority, waived change fees, and lounge access.' },
  { term: 'Corporate Sales Agreement (CSA)', def: 'Delta\'s negotiated program for large enterprises (500+ travelers, $300K+ annual spend). Includes global Corporate Priority, partner airline coverage, unused ticket transfer, and 24/7 support.' },
  { term: 'Delta One', def: 'Delta\'s international business class product, available on transatlantic and transpacific routes and select domestic flights. Includes fully flat beds, premium meals, and lounge access.' },
  { term: 'Delta Business Tool', def: 'Delta\'s platform for integrating corporate booking systems. Connects TMCs, Concur, SAP, and other travel management tools with your Delta for Business account for automated reporting and booking policy enforcement.' },
  { term: 'Dual Earn', def: 'The simultaneous crediting of miles to both the company account and the employee\'s personal SkyMiles account on the same flight. Neither earning reduces the other.' },
  { term: 'eCredits', def: 'Delta travel credits generated by converting company miles through the portal. Worth approximately 1.5–2¢ per mile. Applied to future Delta bookings at checkout. One eCredit per ticket maximum.' },
  { term: 'Elite (SMB Tier)', def: 'The highest SkyMiles for Business company tier, reached at $300K+ annual Delta spend. Earns all Plus benefits plus a 15% bonus on miles and a dedicated account manager.' },
  { term: 'MQD (Medallion Qualifying Dollar)', def: 'The primary metric for earning Delta Medallion status. Based on dollars spent on eligible Delta flights in a calendar year. Silver: $5K, Gold: $10K, Platinum: $15K, Diamond: $28K.' },
  { term: 'Medallion Status', def: 'Delta\'s individual elite status program with four tiers: Silver, Gold, Platinum, and Diamond. Earns benefits like priority boarding, upgrades, lounge access, and SkyMiles bonuses. Entirely separate from SkyMiles for Business.' },
  { term: 'Member (SMB Tier)', def: 'The entry tier of SkyMiles for Business. Free to join. Includes portal access and personalized offers, but does not earn company miles until reaching Plus tier ($5K spend).' },
  { term: 'Mid-Market Sales Agreement (MSA)', def: 'Delta\'s negotiated corporate program for companies spending $50K–$300K annually. Includes custom fares, full Corporate Priority suite, and a dedicated account manager.' },
  { term: 'Plus (SMB Tier)', def: 'The mid tier of SkyMiles for Business, reached at $5K+ annual Delta spend. Earns up to 10 company miles per dollar on eligible flights.' },
  { term: 'SkyMiles', def: 'Delta\'s loyalty currency. Individual travelers earn personal SkyMiles on flights, credit card spending, and partner activity. Used for award flights, upgrades, and companion certificates. Does not expire.' },
  { term: 'SkyMiles for Business', def: 'Delta\'s self-serve corporate travel program for companies of any size. The company and every employee earn miles simultaneously on the same flight at no cost to either.' },
  { term: 'SkyPriority', def: 'A priority service designation available to Medallion members and select corporate travelers. Includes priority check-in, security lanes, baggage handling, and boarding at participating airports.' },
  { term: 'Sky Club', def: 'Delta\'s airport lounge network with 50+ locations worldwide. Access available via select Delta Amex cards, Medallion status, or day passes. Includes Wi-Fi, food, bar, and workspaces.' },
  { term: 'TMC (Travel Management Company)', def: 'A third-party travel agency that manages corporate travel programs. Examples: Amex Global Business Travel, BCD Travel, CWT, Navan. Can integrate with Delta for Business via Delta Business Tool.' },
]

const grouped = terms.reduce<Record<string, typeof terms>>((acc, t) => {
  const letter = t.term[0].toUpperCase()
  if (!acc[letter]) acc[letter] = []
  acc[letter].push(t)
  return acc
}, {})

const letters = Object.keys(grouped).sort()

export default function GlossaryPage() {
  return (
    <main>
      <section className="py-16" style={{ background: 'linear-gradient(135deg, var(--color-delta-blue-700) 0%, var(--color-delta-blue-600) 100%)' }}>
        <div className="mx-auto px-6 lg:px-8 text-center" style={{ maxWidth: 'var(--container-narrow)' }}>
          <h1 style={{ fontSize: 'clamp(1.75rem, 3vw, var(--type-scale-40))', fontFamily: 'var(--font-display)', fontWeight: '700', color: 'var(--color-neutral-0)', marginBottom: '12px' }}>
            Delta for Business Glossary
          </h1>
          <p style={{ fontSize: 'var(--type-scale-16)', color: 'rgba(255,255,255,0.78)' }}>
            Plain-English definitions for every term you might encounter.
          </p>
        </div>
      </section>

      <section className="py-20" style={{ background: 'var(--color-neutral-0)' }}>
        <div className="mx-auto px-6 lg:px-8" style={{ maxWidth: 'var(--container-narrow)' }}>
          {/* Letter navigation */}
          <div className="flex flex-wrap gap-2 mb-12">
            {letters.map((l) => (
              <a
                key={l}
                href={`#letter-${l}`}
                className="w-9 h-9 flex items-center justify-center rounded-full font-bold"
                style={{ background: 'var(--color-neutral-5)', border: '1px solid var(--color-neutral-10)', fontSize: 'var(--type-scale-14)', color: 'var(--color-delta-blue-600)', textDecoration: 'none' }}
              >
                {l}
              </a>
            ))}
          </div>

          {/* Terms */}
          <div className="space-y-10">
            {letters.map((letter) => (
              <div key={letter} id={`letter-${letter}`}>
                <h2
                  style={{
                    fontSize: 'var(--type-scale-32)',
                    fontFamily: 'var(--font-display)',
                    fontWeight: '700',
                    color: 'var(--color-delta-red-400)',
                    marginBottom: '16px',
                    borderBottom: '2px solid var(--color-neutral-10)',
                    paddingBottom: '8px',
                  }}
                >
                  {letter}
                </h2>
                <dl className="space-y-5">
                  {grouped[letter].map((item) => (
                    <div key={item.term}>
                      <dt style={{ fontSize: 'var(--type-scale-16)', fontWeight: '700', color: 'var(--color-delta-blue-700)', marginBottom: '4px' }}>
                        {item.term}
                      </dt>
                      <dd style={{ fontSize: 'var(--type-scale-14)', color: 'var(--color-neutral-600)', lineHeight: 1.7, marginLeft: '0' }}>
                        {item.def}
                      </dd>
                    </div>
                  ))}
                </dl>
              </div>
            ))}
          </div>
        </div>
      </section>
    </main>
  )
}
