import type { Card } from '@/types'

// Agent 1: Complete card data — verify against current Amex offers
export const cards: Record<string, Card> = {
  blue: {
    id: 'blue',
    family: 'personal',
    tier: 'blue',
    name: 'Delta SkyMiles® Blue American Express Card',
    slug: 'blue',
    annualFee: 0,
    firstYearFee: 0,
    welcomeBonus: { miles: 10000, spendRequirement: 500, months: 6 },
    earningRates: [
      { category: 'Delta purchases', rate: '2x' },
      { category: 'Dining', rate: '2x' },
      { category: 'Everything else', rate: '1x' },
    ],
    credits: [],
    mqdHeadstart: 0,
    mqdBoostRate: 'None',
    companionCert: null,
    skyClubAccess: 'None',
    image: '/assets/images/cards/delta-amex-blue-card.png',
    bestFor: 'Casual travelers who want no annual fee',
    applyUrl: 'https://americanexpress.com/delta-blue',
  },
  gold: {
    id: 'gold',
    family: 'personal',
    tier: 'gold',
    name: 'Delta SkyMiles® Gold American Express Card',
    slug: 'gold',
    annualFee: 150,
    firstYearFee: 0,
    welcomeBonus: { miles: 40000, spendRequirement: 2000, months: 6 },
    earningRates: [
      { category: 'Delta purchases', rate: '2x' },
      { category: 'Dining', rate: '2x' },
      { category: 'US supermarkets', rate: '2x' },
      { category: 'Everything else', rate: '1x' },
    ],
    credits: [
      { name: 'Delta Stays credit', amount: 100, frequency: 'annual', description: 'Hotels booked through Delta' },
    ],
    mqdHeadstart: 0,
    mqdBoostRate: '$25 spend = $1 MQD',
    companionCert: { cabin: 'Main Cabin', routes: 'Domestic + Mexico/Caribbean/Central America' },
    skyClubAccess: 'None',
    image: '/assets/images/cards/delta-amex-gold-card.png',
    bestFor: 'Regular travelers who want free first checked bag and companion cert',
    applyUrl: 'https://americanexpress.com/delta-gold',
  },
  platinum: {
    id: 'platinum',
    family: 'personal',
    tier: 'platinum',
    name: 'Delta SkyMiles® Platinum American Express Card',
    slug: 'platinum',
    annualFee: 350,
    firstYearFee: 350,
    welcomeBonus: { miles: 60000, spendRequirement: 3000, months: 6 },
    earningRates: [
      { category: 'Delta purchases', rate: '3x' },
      { category: 'Dining', rate: '2x' },
      { category: 'US supermarkets', rate: '2x' },
      { category: 'Transit', rate: '2x' },
      { category: 'Everything else', rate: '1x' },
    ],
    credits: [
      { name: 'Delta Stays credit', amount: 150, frequency: 'annual', description: 'Hotels booked through Delta' },
    ],
    mqdHeadstart: 2500,
    mqdBoostRate: '$20 spend = $1 MQD',
    companionCert: { cabin: 'Main Cabin', routes: 'Domestic + Mexico/Caribbean/Central America' },
    skyClubAccess: 'Limited (after spending $75K in calendar year)',
    image: '/assets/images/cards/delta-amex-platinum-card.png',
    bestFor: 'Frequent travelers pursuing Medallion status',
    applyUrl: 'https://americanexpress.com/delta-platinum',
  },
  reserve: {
    id: 'reserve',
    family: 'personal',
    tier: 'reserve',
    name: 'Delta SkyMiles® Reserve American Express Card',
    slug: 'reserve',
    annualFee: 650,
    firstYearFee: 650,
    welcomeBonus: { miles: 80000, spendRequirement: 5000, months: 6 },
    earningRates: [
      { category: 'Delta purchases', rate: '3x' },
      { category: 'Dining', rate: '2x' },
      { category: 'Everything else', rate: '1x' },
      { category: 'After $150K spend', rate: '1.5x on everything' },
    ],
    credits: [
      { name: 'Delta Stays credit', amount: 200, frequency: 'annual', description: 'Hotels booked through Delta' },
      { name: 'Resy dining credit', amount: 120, frequency: 'annual', description: '$10/month' },
    ],
    mqdHeadstart: 2500,
    mqdBoostRate: '$15 spend = $1 MQD',
    companionCert: { cabin: 'Delta One or First Class', routes: 'Domestic + int\'l' },
    skyClubAccess: 'Unlimited for cardholder + 2 guests',
    image: '/assets/images/cards/delta-amex-reserve-card.png',
    bestFor: 'Premium travelers wanting Sky Club access and Delta One companion cert',
    applyUrl: 'https://americanexpress.com/delta-reserve',
  },
  'gold-business': {
    id: 'gold-business',
    family: 'business',
    tier: 'gold',
    name: 'Delta SkyMiles® Gold Business American Express Card',
    slug: 'gold-business',
    annualFee: 150,
    firstYearFee: 0,
    welcomeBonus: { miles: 40000, spendRequirement: 2000, months: 6 },
    earningRates: [
      { category: 'Delta purchases', rate: '2x' },
      { category: 'US shipping', rate: '2x' },
      { category: 'US advertising', rate: '2x' },
      { category: 'Everything else', rate: '1x' },
    ],
    credits: [],
    mqdHeadstart: 0,
    mqdBoostRate: '$25 spend = $1 MQD',
    companionCert: { cabin: 'Main Cabin', routes: 'Domestic' },
    skyClubAccess: 'None',
    image: '/assets/images/cards/delta-amex-gold-card.png',
    bestFor: 'Small businesses with moderate Delta travel',
    applyUrl: 'https://americanexpress.com/delta-gold-business',
  },
  'platinum-business': {
    id: 'platinum-business',
    family: 'business',
    tier: 'platinum',
    name: 'Delta SkyMiles® Platinum Business American Express Card',
    slug: 'platinum-business',
    annualFee: 350,
    firstYearFee: 350,
    welcomeBonus: { miles: 60000, spendRequirement: 3000, months: 6 },
    earningRates: [
      { category: 'Delta purchases', rate: '3x' },
      { category: 'US shipping', rate: '2x' },
      { category: 'US advertising', rate: '2x' },
      { category: 'Transit', rate: '2x' },
      { category: 'Everything else', rate: '1x' },
    ],
    credits: [],
    mqdHeadstart: 2500,
    mqdBoostRate: '$20 spend = $1 MQD',
    companionCert: { cabin: 'Main Cabin', routes: 'Domestic' },
    skyClubAccess: 'Limited',
    image: '/assets/images/cards/delta-amex-platinum-card.png',
    bestFor: 'Business owners pursuing Medallion with card spend acceleration',
    applyUrl: 'https://americanexpress.com/delta-platinum-business',
  },
  'reserve-business': {
    id: 'reserve-business',
    family: 'business',
    tier: 'reserve',
    name: 'Delta SkyMiles® Reserve Business American Express Card',
    slug: 'reserve-business',
    annualFee: 650,
    firstYearFee: 650,
    welcomeBonus: { miles: 80000, spendRequirement: 5000, months: 6 },
    earningRates: [
      { category: 'Delta purchases', rate: '3x' },
      { category: 'US shipping', rate: '2x' },
      { category: 'Everything else', rate: '1x' },
      { category: 'After $150K spend', rate: '1.5x on everything' },
    ],
    credits: [],
    mqdHeadstart: 2500,
    mqdBoostRate: '$15 spend = $1 MQD',
    companionCert: { cabin: 'Delta One or First Class', routes: 'Domestic + int\'l' },
    skyClubAccess: 'Unlimited for cardholder + 2 guests',
    image: '/assets/images/cards/delta-amex-reserve-card.png',
    bestFor: 'Business owners wanting Sky Club + maximum Medallion acceleration',
    applyUrl: 'https://americanexpress.com/delta-reserve-business',
  },
}

export const cardOrder = ['blue', 'gold', 'platinum', 'reserve'] as const
export const businessCardOrder = ['gold-business', 'platinum-business', 'reserve-business'] as const
