import type { Segment } from '@/types'

export const segments: Record<string, Segment> = {
  'business-traveler': {
    id: 'business-traveler',
    name: 'Business Traveler',
    shortName: 'Business Traveler',
    tagline: 'Personal travel perks and company-mile earning — zero employer friction.',
    description: 'For individual travelers and small teams. Free self-serve enrollment, dual SkyMiles earning, and partner perks from day one.',
    color: 'var(--color-segment-individual)',
    programType: 'self-serve',
    oldName: 'Individual / SkyMiles for Business (SMB)',
    enrollmentPath: '/enroll/individual',
    minTravelers: 1,
    maxTravelers: 49,
    annualSpend: { min: 0, max: 49999 },
    ctaPrimary: { label: 'Get started free', href: '/enroll/individual' },
    ctaSecondary: { label: 'Learn more', href: '/programs/business-traveler' },
    keyBenefits: [
      'Company earns up to 10 miles per dollar',
      'Employees earn personal SkyMiles simultaneously',
      'eCredit redemptions (~1.5–2¢/mile)',
      'Management dashboard included',
    ],
  },
  enterprise: {
    id: 'enterprise',
    name: 'Enterprise program',
    shortName: 'Enterprise',
    tagline: 'Negotiated fares, Corporate Priority, and a dedicated account manager.',
    description: 'For companies with 50–500 travelers spending $50K+/year. Mid-Market Sales Agreement (MSA) with full Corporate Priority suite.',
    color: 'var(--color-segment-mid)',
    programType: 'negotiated',
    oldName: 'Mid-Market Sales Agreement (MSA)',
    enrollmentPath: '/enroll/enterprise',
    minTravelers: 50,
    maxTravelers: 499,
    annualSpend: { min: 50000, max: 299999 },
    ctaPrimary: { label: 'Contact sales', href: '/enroll/enterprise' },
    ctaSecondary: { label: 'Learn more', href: '/programs/enterprise' },
    keyBenefits: [
      'Negotiated fares off published rates',
      'Full Corporate Priority suite',
      'Dedicated account manager',
      'Concur / TMC integration',
    ],
  },
  'large-enterprise': {
    id: 'large-enterprise',
    name: 'Large-Enterprise program',
    shortName: 'Large Enterprise',
    tagline: 'Full managed travel with global Corporate Priority and Delta SYNC access.',
    description: 'For companies with 500+ travelers spending $300K+. Corporate Sales Agreement (CSA) with global coverage, Delta SYNC, and 24/7 support.',
    color: 'var(--color-segment-enterprise)',
    programType: 'negotiated',
    oldName: 'Corporate Sales Agreement (CSA)',
    enrollmentPath: '/enroll/enterprise',
    minTravelers: 500,
    maxTravelers: null,
    annualSpend: { min: 300000, max: null },
    ctaPrimary: { label: 'Contact sales', href: '/enroll/enterprise' },
    ctaSecondary: { label: 'Learn more', href: '/programs/large-enterprise' },
    keyBenefits: [
      'Full Corporate Priority suite — globally',
      'Partner airlines: AF, KLM, LATAM, Virgin Atlantic',
      'Delta SYNC travel management platform',
      'Unused ticket transfer + 24/7 support',
    ],
  },
}

export const segmentOrder = ['business-traveler', 'enterprise', 'large-enterprise'] as const
