import type { Segment } from '@/types'

export const segments: Record<string, Segment> = {
  'business-traveler': {
    id: 'business-traveler',
    name: 'Gold business plan',
    shortName: 'Gold business plan',
    tagline: 'Company rewards pool, personal perks, and dual SkyMiles earning — free to join.',
    description: '$5K–$50K annual Delta spend (typically accommodates 2 to 49 travelers). Free self-serve enrollment, dual SkyMiles earning, and partner perks from day one.',
    color: 'var(--color-segment-individual)',
    programType: 'self-serve',
    oldName: 'Business Traveler / SkyMiles for Business',
    enrollmentPath: '/enroll/gold',
    minTravelers: 1,
    maxTravelers: 49,
    annualSpend: { min: 0, max: 49999 },
    ctaPrimary: { label: 'Get started free', href: '/enroll/gold' },
    ctaSecondary: { label: 'Learn more', href: '/programs/business-traveler' },
    keyBenefits: [
      'Business rewards pool + dual earning',
      'Threshold-based discounts',
      'Partner perks: Hertz, CLEAR, LinkedIn',
      'Flexibility credits + basic analytics',
    ],
  },
  enterprise: {
    id: 'enterprise',
    name: 'Platinum business plan',
    shortName: 'Platinum business plan',
    tagline: 'Dynamic fares, seat pools, and full Corporate Priority — built for growing teams.',
    description: '$50K–$300K annual Delta spend (typically accommodates 50 to 499 travelers). Negotiated agreement with full Corporate Priority suite.',
    color: 'var(--color-segment-mid)',
    programType: 'negotiated',
    oldName: 'Enterprise program / Mid-Market Sales Agreement (MSA)',
    enrollmentPath: '/enroll/platinum',
    minTravelers: 50,
    maxTravelers: 499,
    annualSpend: { min: 50000, max: 299999 },
    ctaPrimary: { label: 'Contact sales', href: '/enroll/platinum' },
    ctaSecondary: { label: 'Learn more', href: '/programs/enterprise' },
    keyBenefits: [
      'Dynamic fare discounts',
      'Seat access pools + advanced analytics',
      'Account manager + Corporate Priority',
      'Reduced change fees + Concur integration',
    ],
  },
  'large-enterprise': {
    id: 'large-enterprise',
    name: 'Diamond business plan',
    shortName: 'Diamond business plan',
    tagline: 'Custom pricing, full reporting, and dedicated support at global scale.',
    description: '$300K+ annual Delta spend (typically accommodates 500+ travelers). Custom pricing, seat inventory control, full reporting, and dedicated support.',
    color: 'var(--color-segment-enterprise)',
    programType: 'negotiated',
    oldName: 'Large-Enterprise program / Corporate Sales Agreement (CSA)',
    enrollmentPath: '/enroll/diamond',
    minTravelers: 500,
    maxTravelers: null,
    annualSpend: { min: 300000, max: null },
    ctaPrimary: { label: 'Contact sales', href: '/enroll/diamond' },
    ctaSecondary: { label: 'Learn more', href: '/programs/large-enterprise' },
    keyBenefits: [
      'Custom pricing + seat inventory control',
      'Full reporting + forecasting',
      'Dedicated support + Amex integration',
      'All Platinum business plan benefits globally',
    ],
  },
}

export const segmentOrder = ['business-traveler', 'enterprise', 'large-enterprise'] as const
